version: '3'
services:
  node01:
    image: ${APPLIED_IMAGE}
    hostname: node01
    environment:
      - HOSTS=${HOSTS} 
    networks:
      hpl_net:
        ipv4_address: 172.20.0.2

  node02:
    image: ${APPLIED_IMAGE}
    hostname: node02
    environment:
      - HOSTS=${HOSTS} 
    networks:
      hpl_net:
        ipv4_address: 172.20.0.3

  node03:
    image: ${APPLIED_IMAGE}
    hostname: node03
    environment:
      - HOSTS=${HOSTS} 
    networks:
      hpl_net:
        ipv4_address: 172.20.0.4

  node04:
    image: ${APPLIED_IMAGE}
    hostname: node04
    environment:
      - HOSTS=${HOSTS} 
    networks:
      hpl_net:
        ipv4_address: 172.20.0.5

networks:
  hpl_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16